# Generated by Django 4.0.3 on 2022-03-22 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32, verbose_name='employee first name')),
                ('last_name', models.CharField(max_length=32, verbose_name='employee last name')),
                ('job', models.CharField(max_length=50, verbose_name='employee job')),
                ('avatar', models.ImageField(blank=True, null='True', upload_to='employee', verbose_name='employee image')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.department')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
    ]
