# Generated by Django 4.0.3 on 2022-03-22 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='avatar',
            field=models.ImageField(blank=True, null='True', upload_to='image-database', verbose_name='employee image'),
        ),
    ]
