# Generated by Django 4.0.3 on 2022-03-22 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Department name')),
                ('short_name', models.CharField(max_length=20, unique=True, verbose_name='department short name')),
                ('anulate', models.BooleanField(default=False, verbose_name='department in operation')),
            ],
            options={
                'verbose_name': 'Deparment',
                'verbose_name_plural': 'Deparments',
            },
        ),
    ]
